### ISSUE TITLE
recover-buffers not listed on MELPA?

### ISSUE THREAD

**Issue by ReneFroger** [tripleee/recover-buffers#1]
Hi, thanks for sharing this package! It was useful for me, I really appreciate it. Could this perhaps be listed on MELPA?

Thanks in advance!

**Comment by tripleee** [comment]
Thanks for the suggestion!  I created [a pull request](https://github.com/milkypostman/melpa/pull/3012) which I hope will be sufficient for this.  Review and testing would be most welcome.

**Comment by tripleee** [comment]
Merged upstream.  Thanks for the suggestion!
