### ISSUE TITLE
License of the package

### ISSUE THREAD

**Issue by matsl** [tripleee/recover-buffers#2]
Hi,

Could not find any other contact info so opening an issue for this license request.

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html                                                                                                     

So I wonder if you could consider to change the license of your package to GPL-3+?

**Comment by tripleee** [comment]
Dunno how I missed this earlier; thanks for the ping! I have mostly preferred BSD-style licenses but I'll look ito making an exception.

**Comment by tripleee** [comment]
License is now dual GPLv3+ / BSD without advertising clause (was GPL v2 / BSD without adv).

Thanks for the issue; I appreciate your getting in touch, and doing that via a public issue tracker was exactly the right way to do that IMHO.
